apiVersion: spec.keptn.sh/0.2.2
kind: KeptnShipyard
metadata:
    name: ""
spec:
    stages:
        - name: dev
          sequences:
            - name: artifact-delivery
              tasks:
                - name: promotion
                - name: monaco
                - name: deployment
                  properties:
                    deploymentstrategy: user_managed
                - name: smoke-test
                - name: release
        - name: hardening
          sequences:
            - name: artifact-delivery
              triggeredOn:
                - event: dev.artifact-delivery.finished
              tasks:
                - name: promotion
                - name: monaco
                - name: deployment
                  properties:
                    deploymentstrategy: user_managed
                - name: smoke-test
                - name: release
        - name: production
          sequences:
            - name: artifact-delivery
              triggeredOn:
                - event: hardening.artifact-delivery.finished
              tasks:
                - name: promotion
                - name: monaco
                - name: deployment
                  properties:
                    deploymentstrategy: user_managed
                - name: smoke-test
                - name: approval
                  properties:
                    pass: manual
                    warning: manual
                - name: release
